name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Rust and install mdBook
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          bins: mdbook,mdbook-plantuml

      - name: Build Docs
        run: mdbook build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: book
